import csv
import ast
import json
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional


def _safe_json(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, (list, dict)):
        return value
    s = str(value).strip()
    if not s:
        return None
    # Common Postgres→CSV string shapes: '["a","b"]', '{"a":1}', or '{a,b}' (arrays)
    try:
        if s[0] in "[{":
            return json.loads(s)
    except Exception:
        pass

    # CSV exports sometimes produce Python literals like "['English', 'Hebrew']"
    # (single quotes) instead of valid JSON. `literal_eval` is safe (no code exec).
    if s[0] in "[{(" and s[-1] in "]})":
        try:
            return ast.literal_eval(s)
        except Exception:
            pass
    # Attempt to normalize postgres array literal: {a,b}
    if s.startswith("{") and s.endswith("}"):
        inner = s[1:-1].strip()
        if not inner:
            return []
        return [p.strip().strip('"') for p in inner.split(",") if p.strip()]
    return s


def _as_list_str(value: Any) -> list[str]:
    v = _safe_json(value)
    if v is None:
        return []
    if isinstance(v, list):
        return [str(x) for x in v]
    if isinstance(v, tuple):
        return [str(x) for x in v]
    # Allow comma-separated convenience
    if isinstance(v, str) and "," in v:
        return [p.strip() for p in v.split(",") if p.strip()]
    return [str(v)]


def _as_bool(value: Any, default: bool = False) -> bool:
    if value is None or value == "":
        return default
    if isinstance(value, bool):
        return value
    s = str(value).strip().lower()
    return s in {"1", "t", "true", "yes", "y"}


def _as_int(value: Any, default: int = 0) -> int:
    if value is None or value == "":
        return default
    try:
        return int(float(value))
    except Exception:
        return default


def _as_float(value: Any, default: float = 0.0) -> float:
    if value is None or value == "":
        return default
    try:
        return float(value)
    except Exception:
        return default


def _parse_time_hhmmss(value: Any) -> Optional[str]:
    if value is None or value == "":
        return None
    s = str(value).strip()
    if len(s) >= 5:
        return s[:5]
    return None


def _parse_date(value: Any) -> Optional[datetime]:
    if value is None or value == "":
        return None
    s = str(value).strip()
    try:
        # e.g. 2026-03-22
        dt = datetime.strptime(s[:10], "%Y-%m-%d")
        return dt.replace(tzinfo=timezone.utc)
    except Exception:
        return None


def _parse_iso_dt(value: Any) -> Optional[datetime]:
    if value is None or value == "":
        return None
    s = str(value).strip()
    try:
        # allow '2026-03-22 17:30:00+00' or ISO
        s = s.replace(" ", "T")
        dt = datetime.fromisoformat(s)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except Exception:
        return None


@dataclass(frozen=True)
class CsvDataHealth:
    teachers: int
    students: int
    classes: int
    teacher_availability_rows: int
    teacher_holidays_rows: int
    leads: int
    teacher_performance_profile: int
    notes: list[str]


class CsvRepository:
    """
    CSV-backed repository for demos when Postgres is incomplete.
    Files are expected under `ml/data/` as generated by `export_csv.py`.
    All timestamps are treated as UTC.
    """

    def __init__(self, data_dir: Path):
        self.data_dir = data_dir
        self._teachers: dict[int, dict[str, Any]] = {}
        self._students: dict[int, dict[str, Any]] = {}
        self._classes: list[dict[str, Any]] = []
        # Performance index: teacher_id -> list of parsed class intervals (UTC datetimes)
        self._classes_by_teacher: dict[int, list[dict[str, Any]]] = {}
        self._availability: list[dict[str, Any]] = []
        self._holidays: list[dict[str, Any]] = []
        self._subscriptions: list[dict[str, Any]] = []
        self._leads: list[dict[str, Any]] = []
        self._performance: dict[int, dict[str, Any]] = {}

        self._dummy_teachers: dict[int, dict[str, Any]] = {}
        self._dummy_students: dict[int, dict[str, Any]] = {}
        self._teachers_with_lang_fallback: int = 0  # count of teachers given [English] when CSV was empty

        self.reload()

    def reload(self) -> None:
        self._teachers = self._load_teachers()
        self._students = self._load_students()
        self._classes = self._load_classes()
        # Build an index so recurring/trial conflict checks don't scan whole classes.csv.
        idx: dict[int, list[dict[str, Any]]] = {}
        for c in self._classes:
            tid = _as_int(c.get("teacher_id"), 0)
            if tid <= 0:
                continue
            ms = _parse_iso_dt(c.get("meeting_start"))
            me = _parse_iso_dt(c.get("meeting_end")) or (
                ms + timedelta(minutes=30) if ms else None
            )
            if not ms or not me:
                continue
            status = str(c.get("lifecycle_status") or "").lower()
            if status in {"cancelled", "canceled", "no_show"}:
                continue
            idx.setdefault(tid, []).append(
                {
                    "meeting_start": ms,
                    "meeting_end": me,
                    "student_id": c.get("student_id"),
                }
            )
        self._classes_by_teacher = idx
        self._availability = self._load_teacher_availability()
        self._holidays = self._load_teacher_holidays()
        self._subscriptions = self._load_subscriptions()
        self._leads = self._load_leads()
        self._performance = self._load_teacher_performance_profile()

    # ─────────────────────────────────────────────────────────────
    # Health
    # ─────────────────────────────────────────────────────────────

    def health(self) -> CsvDataHealth:
        notes: list[str] = []
        if not self._teachers:
            notes.append("teachers.csv is empty or missing")
        if not self._students:
            notes.append("students.csv is empty or missing")
        if self._teachers and not self._availability:
            notes.append("teacher_availability.csv is empty/missing — recurring matching will return no results")

        # Reconciliation checks: CSV dumps can be inconsistent between files.
        try:
            active_teacher_ids = {
                int(tid)
                for tid, t in self._teachers.items()
                if str(t.get("status") or "active").lower() == "active"
            }
            availability_teacher_ids = {
                _as_int(r.get("teacher_id"), 0)
                for r in self._availability
            }
            availability_teacher_ids.discard(0)

            missing_profiles = availability_teacher_ids - active_teacher_ids
            if missing_profiles:
                sample = sorted(missing_profiles)[:5]
                notes.append(
                    f"Availability references {len(missing_profiles)} teacher_id(s) with no active profile in teachers.csv (e.g. {sample})"
                )

            missing_availability = active_teacher_ids - availability_teacher_ids
            if missing_availability:
                sample = sorted(missing_availability)[:5]
                notes.append(
                    f"teachers.csv has {len(missing_availability)} active teacher_id(s) with no matching teacher_availability rows (e.g. {sample})"
                )

            if self._teachers_with_lang_fallback:
                notes.append(
                    f"{self._teachers_with_lang_fallback} teacher(s) had empty teaching_languages in CSV; "
                    "treated as [English] for demo matching (regenerate CSV for accurate data)"
                )
        except Exception:
            # health must be non-fatal; we only want best-effort diagnostics
            pass

        return CsvDataHealth(
            teachers=len(self._teachers) + len(self._dummy_teachers),
            students=len(self._students) + len(self._dummy_students),
            classes=len(self._classes),
            teacher_availability_rows=len(self._availability),
            teacher_holidays_rows=len(self._holidays),
            leads=len(self._leads),
            teacher_performance_profile=len(self._performance),
            notes=notes,
        )

    # ─────────────────────────────────────────────────────────────
    # Demo mutation (dummy entities)
    # ─────────────────────────────────────────────────────────────

    def add_dummy_teacher(self, teacher: dict[str, Any]) -> dict[str, Any]:
        tid = _as_int(teacher.get("teacher_id") or teacher.get("id") or 0, 0)
        if tid <= 0:
            # Allocate a synthetic id
            tid = (max([0, *self._teachers.keys(), *self._dummy_teachers.keys()]) or 0) + 1
        normalized = {
            "teacher_id": tid,
            "full_name": str(teacher.get("full_name") or teacher.get("name") or f"Teacher {tid}"),
            "status": "active",
            "teaching_languages": _as_list_str(teacher.get("teaching_languages") or ["English"]),
            "trial_enabled": _as_bool(teacher.get("trial_enabled"), True),
            "age_min": _as_int(teacher.get("age_min"), 5),
            "age_max": _as_int(teacher.get("age_max"), 18),
            "teacher_tags": _as_list_str(teacher.get("teacher_tags") or []),
            "languages_spoken": _as_list_str(teacher.get("languages_spoken") or []),
            "max_students_capacity": _as_int(teacher.get("max_students_capacity"), 20),
            "trial_priority": str(teacher.get("trial_priority") or "normal"),
        }
        self._dummy_teachers[tid] = normalized

        # Optional: also inject recurring availability so the demo can produce slots.
        # Expected fields (all optional):
        # - availability_days: e.g. ["Sunday","Tuesday"] or "Sunday, Tuesday"
        # - availability_start_time: "16:00"
        # - availability_end_time: "21:00"
        availability_days_raw = teacher.get("availability_days") or teacher.get("availabilityDays") or ["Sunday"]
        availability_days = _as_list_str(availability_days_raw)
        start_time = str(teacher.get("availability_start_time") or teacher.get("availability_from") or "16:00")[:5]
        end_time = str(teacher.get("availability_end_time") or teacher.get("availability_to") or "21:00")[:5]

        day_key_to_idx = {"sun": 0, "mon": 1, "tue": 2, "wed": 3, "thu": 4, "fri": 5, "sat": 6}
        injected = 0
        for d in availability_days:
            d_l = str(d).strip().lower()
            d_key = d_l[:3] if d_l else ""
            if d_key not in day_key_to_idx:
                continue
            day_idx = day_key_to_idx[d_key]
            # The matching engine expands this into 30-min slots.
            self._availability.append(
                {
                    "availability_id": f"dummy_{tid}_{day_idx}_{injected}",
                    "teacher_id": tid,
                    "day_of_week": str(day_idx),
                    "start_time": f"{start_time}:00",
                    "end_time": f"{end_time}:00",
                    "is_active": "True",
                }
            )
            injected += 1

        # If dummy availability injection is impossible (bad inputs), we still keep the teacher profile.
        # The /match endpoint will simply return 0 slots, and /demo/data-health will explain why.
        return normalized

    def add_dummy_student(self, student: dict[str, Any]) -> dict[str, Any]:
        sid = _as_int(student.get("student_id") or student.get("id") or 0, 0)
        if sid <= 0:
            sid = (max([0, *self._students.keys(), *self._dummy_students.keys()]) or 0) + 1
        normalized = {
            "student_id": sid,
            "full_name": str(student.get("full_name") or student.get("name") or f"Student {sid}"),
            "native_language": student.get("native_language"),
            "cefr_level": student.get("cefr_level") or student.get("english_level"),
            "student_age": _as_int(student.get("student_age") or student.get("age") or 0, 0) or None,
            "target_language": student.get("target_language") or "English",
            "requires_native_language_teacher": _as_bool(student.get("requires_native_language_teacher"), False),
            "preferred_days": _as_list_str(student.get("preferred_days") or []),
            "preferred_time_start": _parse_time_hhmmss(student.get("preferred_time_start")) or "16:00",
            "preferred_time_end": _parse_time_hhmmss(student.get("preferred_time_end")) or "21:00",
            "sessions_per_week": _as_int(student.get("sessions_per_week"), 1),
            "learning_goal": student.get("learning_goal") or "",
        }
        self._dummy_students[sid] = normalized
        return normalized

    # ─────────────────────────────────────────────────────────────
    # Read APIs used by the matching engine
    # ─────────────────────────────────────────────────────────────

    def get_student(self, student_id: int) -> Optional[dict[str, Any]]:
        return self._dummy_students.get(student_id) or self._students.get(student_id)

    def get_teachers_active(self) -> list[dict[str, Any]]:
        teachers = [*self._teachers.values(), *self._dummy_teachers.values()]
        return [t for t in teachers if str(t.get("status")).lower() == "active"]

    def get_teacher_availability_rows(self, teacher_id: int) -> list[dict[str, Any]]:
        return [r for r in self._availability if _as_int(r.get("teacher_id"), 0) == teacher_id and _as_bool(r.get("is_active"), True)]

    def get_teacher_holidays_rows(self, teacher_id: int) -> list[dict[str, Any]]:
        return [r for r in self._holidays if _as_int(r.get("teacher_id"), 0) == teacher_id]

    def get_best_active_subscription_plan_name_for_owner(self, owner_student_id: int) -> Optional[str]:
        """
        Best-effort helper for CSV mode.
        Returns the `plan_name` for the student's most relevant active subscription.
        """
        if not owner_student_id:
            return None

        best_classes_remaining = -1
        best_subscription_id = -1
        best_plan_name: Optional[str] = None

        for s in self._subscriptions:
            if _as_int(s.get("owner_student_id"), 0) != owner_student_id:
                continue
            if str(s.get("status") or "").lower() != "active":
                continue

            classes_remaining = _as_int(s.get("classes_remaining"), 0)
            subscription_id = _as_int(s.get("subscription_id"), 0)
            plan_name = s.get("plan_name")

            if classes_remaining > best_classes_remaining or (
                classes_remaining == best_classes_remaining and subscription_id > best_subscription_id
            ):
                best_classes_remaining = classes_remaining
                best_subscription_id = subscription_id
                best_plan_name = plan_name

        return str(best_plan_name) if best_plan_name is not None else None

    def get_classes_for_teacher_between(self, teacher_id: int, start: datetime, end: datetime) -> list[dict[str, Any]]:
        out: list[dict[str, Any]] = []
        for c in self._classes_by_teacher.get(teacher_id, []):
            ms = c["meeting_start"]
            me = c["meeting_end"]
            if ms < end and me > start:
                out.append(c)
        return out

    def conversion_rate_by_teacher(self) -> dict[int, float]:
        """
        Uses leads.csv funnel_stage and converted_student_id, similar to DB logic.
        """
        converted_students = {int(l["converted_student_id"]) for l in self._leads if l.get("converted_student_id") and str(l.get("funnel_stage")) == "converted"}
        demo_or_converted = {int(l["converted_student_id"]) for l in self._leads if l.get("converted_student_id") and str(l.get("funnel_stage")) in {"demo_done", "converted"}}
        teacher_trials: dict[int, set[int]] = {}
        teacher_demo_pool: dict[int, set[int]] = {}

        for c in self._classes:
            tid = _as_int(c.get("teacher_id"), 0)
            sid = _as_int(c.get("student_id"), 0)
            if tid <= 0 or sid <= 0:
                continue
            # trial classes defined by is_trial or subscription_id null
            is_trial = _as_bool(c.get("is_trial"), False) or (not c.get("subscription_id"))
            if not is_trial:
                continue
            if sid in converted_students:
                teacher_trials.setdefault(tid, set()).add(sid)
            if sid in demo_or_converted:
                teacher_demo_pool.setdefault(tid, set()).add(sid)

        rates: dict[int, float] = {}
        for tid, demo_students in teacher_demo_pool.items():
            denom = len(demo_students)
            if denom <= 0:
                rates[tid] = 0.0
                continue
            numer = len(teacher_trials.get(tid, set()))
            rates[tid] = round(min((numer / denom) * 100.0, 100.0), 1)
        return rates

    def retention_rate_by_teacher(self) -> dict[int, float]:
        return {tid: round(_as_float(p.get("student_retention_rate"), 0.0), 1) for tid, p in self._performance.items()}

    def quality_score_by_teacher(self) -> dict[int, float]:
        # class_facts not exported by default; use avg_rating*20 as a stand-in for demo reliability
        out: dict[int, float] = {}
        for tid, p in self._performance.items():
            out[tid] = round(_as_float(p.get("avg_rating"), 0.0) * 20.0, 1)
        return out

    def current_students_by_teacher(self) -> dict[int, int]:
        # In demo mode: approximate as unique active student_id in classes for teacher
        active = {"confirmed", "in_progress", "completed_raw", "completed_ai", "verified"}
        mapping: dict[int, set[int]] = {}
        for c in self._classes:
            status = str(c.get("lifecycle_status") or "").lower()
            if status not in active:
                continue
            tid = _as_int(c.get("teacher_id"), 0)
            sid = _as_int(c.get("student_id"), 0)
            if tid and sid:
                mapping.setdefault(tid, set()).add(sid)
        return {tid: len(sids) for tid, sids in mapping.items()}

    # ─────────────────────────────────────────────────────────────
    # CSV file loaders
    # ─────────────────────────────────────────────────────────────

    def _load_csv(self, filename: str) -> list[dict[str, Any]]:
        path = self.data_dir / filename
        if not path.exists():
            return []
        with path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            return [row for row in reader]

    def _load_teachers(self) -> dict[int, dict[str, Any]]:
        rows = self._load_csv("teachers.csv")
        out: dict[int, dict[str, Any]] = {}
        fallback_count = 0
        for r in rows:
            tid = _as_int(r.get("teacher_id"), 0)
            if tid <= 0:
                continue
            teaching_languages = _as_list_str(r.get("teaching_languages"))
            languages_spoken = _as_list_str(r.get("languages_spoken"))
            # Demo fallback: many CSV exports have empty teaching_languages; treat as English so
            # teachers with availability can match. Long-term fix: regenerate CSV with full data.
            if not teaching_languages and not languages_spoken:
                teaching_languages = ["English"]
                fallback_count += 1
            elif not teaching_languages:
                teaching_languages = languages_spoken  # use spoken as teaching
                fallback_count += 1
            out[tid] = {
                "teacher_id": tid,
                "full_name": r.get("full_name") or "",
                "status": r.get("status") or "active",
                "teaching_languages": teaching_languages,
                "trial_enabled": _as_bool(r.get("trial_enabled"), True),
                "age_min": _as_int(r.get("age_min"), 5),
                "age_max": _as_int(r.get("age_max"), 18),
                "teacher_tags": _as_list_str(r.get("teacher_tags")),
                "languages_spoken": languages_spoken or teaching_languages,
                "max_students_capacity": _as_int(r.get("max_students_capacity"), 20),
                "trial_priority": str(r.get("trial_priority") or "normal"),
            }
        self._teachers_with_lang_fallback = fallback_count
        return out

    def _load_students(self) -> dict[int, dict[str, Any]]:
        rows = self._load_csv("students.csv")
        out: dict[int, dict[str, Any]] = {}
        for r in rows:
            sid = _as_int(r.get("student_id"), 0)
            if sid <= 0:
                continue
            out[sid] = {
                "student_id": sid,
                "full_name": r.get("full_name") or "",
                "name": r.get("full_name") or "",
                "native_language": r.get("native_language"),
                "cefr_level": r.get("cefr_level"),
                "english_level": r.get("cefr_level"),
                "student_age": _as_int(r.get("student_age"), 0) or None,
                "target_language": r.get("target_language") or "English",
                "requires_native_language_teacher": _as_bool(r.get("requires_native_language_teacher"), False),
                "preferred_days": _as_list_str(r.get("preferred_days")),
                "preferred_time_start": _parse_time_hhmmss(r.get("preferred_time_start")),
                "preferred_time_end": _parse_time_hhmmss(r.get("preferred_time_end")),
                "sessions_per_week": _as_int(r.get("sessions_per_week"), 1),
                "learning_goal": r.get("learning_goal") or "",
            }
        return out

    def _load_classes(self) -> list[dict[str, Any]]:
        return self._load_csv("classes.csv")

    def _load_teacher_availability(self) -> list[dict[str, Any]]:
        return self._load_csv("teacher_availability.csv")

    def _load_teacher_holidays(self) -> list[dict[str, Any]]:
        return self._load_csv("teacher_holidays.csv")

    def _load_subscriptions(self) -> list[dict[str, Any]]:
        return self._load_csv("subscriptions.csv")

    def _load_leads(self) -> list[dict[str, Any]]:
        return self._load_csv("leads.csv")

    def _load_teacher_performance_profile(self) -> dict[int, dict[str, Any]]:
        rows = self._load_csv("teacher_performance_profile.csv")
        out: dict[int, dict[str, Any]] = {}
        for r in rows:
            tid = _as_int(r.get("teacher_id"), 0)
            if tid <= 0:
                continue
            out[tid] = r
        return out

